#  Copyright (c) 2012-2013, Puzzle ITC GmbH. This file is part of
#  hitobito_generic and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_generic.

application:
  name: CVP
  # The languages available in the menu
  languages:
    de: Deutsch
    fr: Français
    en: English
  footer:
    links:
      "Forum": https://hitobito.discoursehosting.net/
      "Dokumentation": https://hitobito.readthedocs.io
      "E-Mail an Support": 'mailto:support@hitobito.com'
pwa:
  short_name: CVP
  theme_color: "#EF7D00"
  icon_sizes: [192, 512]
